  name: my_first_action
  on:
    pull_request:
    push:
      branches:
        - main
  jobs:
    build:
      name: my_update_job
      runs-on: ubuntu-latest
      steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.AIR }}
          run:
            cd ~/airflow/dags
            git pull https://github.com/bodya/dags.git

